"""empty message

Revision ID: 13d4edb6b9c1
Revises: 
Create Date: 2024-02-18 00:11:42.591989

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '13d4edb6b9c1'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('Users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=255), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('password_hash', sa.String(length=255), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email'),
    sa.UniqueConstraint('username')
    )
    op.create_table('Navios',
    sa.Column('id_navio', sa.Integer(), nullable=False),
    sa.Column('nome', sa.String(length=255), nullable=False),
    sa.Column('loa', sa.Float(), nullable=False),
    sa.Column('boca', sa.Float(), nullable=False),
    sa.Column('dwt', sa.Float(), nullable=False),
    sa.Column('calado_entrada', sa.Float(), nullable=False),
    sa.Column('calado_saida', sa.Float(), nullable=False),
    sa.Column('calado_aereo', sa.Float(), nullable=False),
    sa.Column('pontal', sa.Float(), nullable=False),
    sa.Column('tamanho_lanca', sa.Float(), nullable=False),
    sa.Column('ano_construcao', sa.Integer(), nullable=False),
    sa.Column('tipo_navio', sa.String(length=50), nullable=False),
    sa.Column('situacao', sa.String(length=50), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['Users.id'], name='fk_user_id'),
    sa.PrimaryKeyConstraint('id_navio'),
    sa.UniqueConstraint('nome')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('Navios')
    op.drop_table('Users')
    # ### end Alembic commands ###
