"""empty message

Revision ID: 5a4dba85e201
Revises: 6d5d7a1dbd67
Create Date: 2024-02-19 22:33:23.163432

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5a4dba85e201'
down_revision = '6d5d7a1dbd67'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('Navios', schema=None) as batch_op:
        batch_op.add_column(sa.Column('data_cadastro', sa.DateTime(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('Navios', schema=None) as batch_op:
        batch_op.drop_column('data_cadastro')

    # ### end Alembic commands ###
