"""empty message

Revision ID: cc1ef3ea9078
Revises: 5a4dba85e201
Create Date: 2024-02-19 22:34:06.926379

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'cc1ef3ea9078'
down_revision = '5a4dba85e201'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('Navios', schema=None) as batch_op:
        batch_op.alter_column('data_cadastro',
               existing_type=sa.DATETIME(),
               nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('Navios', schema=None) as batch_op:
        batch_op.alter_column('data_cadastro',
               existing_type=sa.DATETIME(),
               nullable=True)

    # ### end Alembic commands ###
