"""tabela user_navio

Revision ID: d4579dfd7748
Revises: 3542ef1bec03
Create Date: 2024-02-08 23:54:51.012700

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd4579dfd7748'
down_revision = '3542ef1bec03'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('Navios', schema=None) as batch_op:
        pass

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('Navios', schema=None) as batch_op:
        pass

    # ### end Alembic commands ###
